// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class MisaMF152002Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void misaMF152002() {
    driver.get("https://www.misa.vn/");
    driver.manage().window().setSize(new Dimension(956, 574));
    driver.findElement(By.cssSelector(".td-icon-font")).click();
    {
      WebElement element = driver.findElement(By.linkText("Hợp tác"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Công ty")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.linkText("Tuyển dụng")).click();
    driver.findElement(By.linkText("Tin tuyển dụng")).click();
    driver.findElement(By.id("searchWorkPlace")).click();
    driver.findElement(By.id("searchWorkPlace")).sendKeys("ha ");
    driver.findElement(By.cssSelector("#listWorkPlace > .lbl-checkbox-wrap:nth-child(2) > .checkmark")).click();
    driver.findElement(By.cssSelector("#listCareer > .lbl-checkbox-wrap:nth-child(10) > .checkmark")).click();
    driver.findElement(By.cssSelector("#listCareer > .lbl-checkbox-wrap:nth-child(6) > .checkmark")).click();
    driver.findElement(By.cssSelector("#listCareer > .lbl-checkbox-wrap:nth-child(5) > .checkmark")).click();
    driver.findElement(By.cssSelector("#listCareer > .lbl-checkbox-wrap:nth-child(11) > .checkmark")).click();
    driver.findElement(By.cssSelector(".job-item:nth-child(6) .job-name")).click();
  }
}
