// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class MisaMF152001Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void misaMF152001() {
    driver.get("https://www.misa.vn/");
    driver.manage().window().setSize(new Dimension(956, 574));
    js.executeScript("window.scrollTo(0,900)");
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".i-amis")).click();
    vars.put("win692", waitForWindow(2000));
    driver.switchTo().window(vars.get("win692").toString());
    js.executeScript("window.scrollTo(0,700)");
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.id("dungthu-loiIch")).click();
    vars.put("win4766", waitForWindow(2000));
    driver.switchTo().window(vars.get("win4766").toString());
    driver.findElement(By.name("firstname")).sendKeys("tuan");
    driver.findElement(By.name("lastname")).click();
    driver.findElement(By.name("lastname")).sendKeys("nguyen");
    driver.findElement(By.name("phone")).click();
    driver.findElement(By.name("phone")).sendKeys("0913032924");
  }
}
