// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class MisaMF152004Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void misaMF152004() {
    driver.get("https://www.misa.vn/");
    driver.manage().window().setSize(new Dimension(1616, 876));
    driver.findElement(By.linkText("Công ty")).click();
    {
      WebElement element = driver.findElement(By.linkText("Khiếu nại"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".col-md-offset-1 > .button > a")).click();
    vars.put("win9300", waitForWindow(2000));
    driver.switchTo().window(vars.get("win9300").toString());
    js.executeScript("window.scrollTo(0,1200)");
    driver.findElement(By.cssSelector(".hp-pi-row:nth-child(4) > .hp-pi-information a")).click();
    driver.findElement(By.linkText("Khám phá")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.id("dungthu-tongquan")).click();
    vars.put("win3811", waitForWindow(2000));
    driver.switchTo().window(vars.get("win3811").toString());
    driver.findElement(By.name("firstname")).sendKeys("tuan");
  }
}
